stages:
  - compile
  - release

compilation:
  stage: compile
  before_script:
    - nuget restore
    - mkdir winagent/lib
    - wget https://github.com/cern-winagent/plugin/releases/latest/download/plugin.dll -OutFile winagent/lib/plugin.dll
  script:
    - msbuild /p:VersionAssembly=$env:CI_COMMIT_TAG /p:Configuration=Release winagent.sln
  after_script:
    - (Get-FileHash winagent/bin/Release/winagent.exe -Algorithm SHA1).Hash > winagent/bin/Release/winagent.exe.sha1
  artifacts:
    paths:
      - winagent/bin/Release/winagent.exe
      - winagent/bin/Release/winagent.exe.sha1
    expire_in: 1 year

# This needs to be changed by GitLab
# Release creation should be 'keyword based'
release:
  stage: release
  only: 
    - tags
  script: 
    # Create a release for the current tag
    - C:\Scripts\CreateRelease.ps1
    # Update "latest" release links with the new artifacts
    - C:\Scripts\UpdateLatestRelease.ps1